config/routes.rb
Rails.application.routes.draw do
  
  resources :veiculos
  resources :especialidades
  resources :formulas
  resources :pedidos
  resources :update_produtos do
   get 'update_produtos'  , as: 'update_produtos'
  end
  resources :update_formulas do
   get 'update_formulas'  , as: 'update_formulas'
  end  
  resources :update_ingredientes do
   get 'update_ingredientes'  , as: 'update_ingredientes'
  end  
  resources :update_veiculo_formula do
   get 'update_veiculo_formula'  , as: 'update_veiculo_formula'
  end    
  resources :pedidos do 
      get 'export'
    end
  resources :produtos
  resources :unidades
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
    get "/editar/:id" => "users#editar", as: :editar_usuario
end

app/models/diluente.rb
class Diluente < ApplicationRecord
  belongs_to :produto
  belongs_to :veiculo
end

app/models/especialidade.rb
class Especialidade < ApplicationRecord
end

app/models/formula.rb
class Formula < ApplicationRecord
	has_many :ingredientes, inverse_of: :formula
	validates_presence_of :nome
	has_one :ingrediente
	belongs_to :especialidade
	belongs_to :veiculo, optional: true
	belongs_to :unidade, optional: true
	accepts_nested_attributes_for :ingredientes, :reject_if => :all_blank, :allow_destroy => true

end

app/models/grupo.rb
class Grupo < ApplicationRecord
  belongs_to :produto
  belongs_to :especialidade
end

app/models/ingrediente.rb
class Ingrediente < ApplicationRecord
  belongs_to        :formula
  belongs_to        :produto
  belongs_to        :unidade
  belongs_to        :especialidade, optional: true
  validate :VerificaUnidadeMedida
  validates_presence_of :produto, :quantidade, :unidade

protected
  def VerificaUnidadeMedida
    quantidade_formula      = self.quantidade
    quantidade_produto      = self.produto.maximo
    unidade_formula         = self.unidade.unidade
    unidade_produto         = self.produto.unidade.unidade
    fator_produto           = self.produto.unidade.fator
    fator_formula           = self.unidade.fator
    verifica = false
    conversao_unidade_formula = quantidade_formula * fator_formula
    conversao_unidade_produto = quantidade_produto * fator_produto

    unless quantidade_produto.nil?
      if conversao_unidade_formula > conversao_unidade_produto
      	verifica = false
      	errors.add(:quantidade, 'Quantidade inválida')
      end
    end

    verifica 
 end



end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :pedido
  belongs_to :produto
  belongs_to :unidade
  belongs_to :especialidade, optional: true
  belongs_to :veiculo, optional: true
  validate :VerificaUnidadeMedida
  validates_presence_of :produto, :quantidade, :unidade

  
protected
  def VerificaUnidadeMedida

    if self.produto.nil?
        verifica = false
        errors.add(:produto, 'Produto inválido')
        return verifica
    end

    if self.quantidade.nil?
        verifica = false
        errors.add(:quantidade, 'Quantidade inválida')
        return verifica
    end


    quantidade_item	        = self.quantidade
    quantidade_produto      = self.produto.maximo
    unidade_item            = self.unidade.unidade
    unidade_produto         = self.produto.unidade.unidade
    fator_produto           = self.produto.unidade.fator
    fator_item	            = self.unidade.fator
    verifica = false
    conversao_unidade_item = quantidade_item * fator_item
    conversao_unidade_produto = quantidade_produto * fator_produto

    unless quantidade_produto.nil?
      if conversao_unidade_item > conversao_unidade_produto
      	verifica = false
      	errors.add(:quantidade, 'Quantidade inválida')
      end
    end
    verifica
 end


end

app/models/manipulado.rb
class Manipulado < ApplicationRecord
  belongs_to :pedido
  belongs_to :formula
  belongs_to :especialidade, optional: true
  belongs_to :veiculo, optional: true
  belongs_to :unidade, optional: true
  has_many   :pontos,  inverse_of: :manipulado, :dependent => :delete_all
  accepts_nested_attributes_for :pontos, :reject_if => :all_blank, :allow_destroy => true
end

app/models/pai.rb
class Pai < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
	belongs_to :user
	has_many :items, inverse_of: :pedido
	has_many :manipulados, inverse_of: :pedido
	accepts_nested_attributes_for :items, :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :manipulados, :reject_if => :all_blank, :allow_destroy => true
	validates_presence_of :paciente
	has_one :item
end
 

app/models/permissao.rb
class Permissao < ApplicationRecord
  belongs_to :user
  belongs_to :especialidade
end

app/models/ponto.rb
class Ponto < ApplicationRecord
  belongs_to :manipulado
  belongs_to :produto
  belongs_to :unidade
  validates_presence_of :produto
end

app/models/produto.rb
class Produto < ApplicationRecord
	belongs_to :unidade
	has_many :grupos, inverse_of: :produto
	has_many :diluentes, inverse_of: :produto
	validates_presence_of :descricao, :unidade
	accepts_nested_attributes_for :grupos , :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :diluentes , :reject_if => :all_blank, :allow_destroy => true

	def to_s
		descricao
	end

end

app/models/unidade.rb
class Unidade < ApplicationRecord
	belongs_to :pai
	validates_presence_of :unidade, :descricao, :pai, :fator
end

app/models/user.rb
class User < ApplicationRecord
  has_many :permissaos, inverse_of: :user
  has_many :pedidos, inverse_of: :user
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user 
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         accepts_nested_attributes_for :permissaos, :reject_if => :all_blank, :allow_destroy => true
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/formulas_helper.rb
module FormulasHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/visitors/index.html.erb
<div id="wrapper">

    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li>
                <a href="#">Dashboard</a>
            </li>
            <li>
                <a href="/produtos">Produtos</a>
            </li>
            <li>
                <% if current_user.role == "admin" %>
                <%= link_to 'Unidades de medida', unidades_path %>
                <%= link_to 'Cadastro de Grupos', especialidades_path %>
                <%= link_to 'Cadastro de Veículos', veiculos_path %>
                <% end %>
            </li>
            <li>
                <a href="/pedidos">Receitas</a>
            </li>
            <li>
                <a href="/formulas">Fórmulas</a>
            </li>            
        </ul>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
         <!--        <div class="col-lg-6" id="grafico1"> -->
                    <% if current_user.role == "admin" %>
                    <%= pie_chart Item.joins(:produto).group(:produto).count, title: "Produtos mais receitados", refresh: 60, width: "800px", height: "500px", download: true %>
                    <% else %>
                    <%= column_chart Pedido.where(' user_id = ?', current_user.id).group_by_day_of_week(:created_at, format: "%a").count, title: "Total de receitas Emitidas", refresh: 60,width: "800px", height: "500px", download: true %>
                    <% end %>
         <!--        </div> -->
            </div>
            <div class="row">
            <!--     <div class="col-lg-6" id="grafico2"> -->
                    <% if current_user.role == "admin" %>
                    <%= pie_chart Manipulado.joins(:formula).group(:nome).count, title: "Fórmulas mais receitados", refresh: 60, width: "800px", height: "500px", download: true %>                    
                    <% end %>
            <!--     </div> -->
            </div>
                <br><br>
            </div>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>            
            <div class="row">
                <!-- <div class="col-lg-6" id="grafico3"> -->
                    <% if current_user.role == "admin" %>
                    <%= pie_chart Pedido.joins(:user).group(:name).count, title: "Receitas por médico", refresh: 60, width: "800px", height: "500px", download: true %>
                    <% end %>
                <!-- </div> -->
            </div>
            <div class="row">
                <!-- <div class="col-lg-6" id="grafico4"> -->
                    <% if current_user.role == "admin" %>
                    <%= column_chart Pedido.group_by_day_of_week(:created_at, format: "%a").count, title: "Total de receitas Emitidas", refresh: 60, width: "800px", height: "500px", download: true %>
                    <% end %>
                <!-- </div>-->
            </div>
            </div>            
        </div>
    </div>
    <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- Menu Toggle Script -->
<script>
$("#menu-toggle").click(function(e) {
    e.preventDefault();
    $("#wrapper").toggleClass("toggled");
});
</script>