config/routes.rb
Rails.application.routes.draw do
  
  resources :veiculos
  resources :especialidades
  resources :formulas
  resources :pedidos
  resources :update_produtos do
   get 'update_produtos'  , as: 'update_produtos'
  end
  resources :update_formulas do
   get 'update_formulas'  , as: 'update_formulas'
  end  
  resources :update_ingredientes do
   get 'update_ingredientes'  , as: 'update_ingredientes'
  end  
  resources :update_veiculo_formula do
   get 'update_veiculo_formula'  , as: 'update_veiculo_formula'
  end    
  resources :pedidos do 
      get 'export'
    end
  resources :produtos
  resources :unidades
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
    get "/editar/:id" => "users#editar", as: :editar_usuario
end

app/models/pedido.rb
class Pedido < ApplicationRecord
	belongs_to :user
	has_many :items, inverse_of: :pedido
	has_many :manipulados, inverse_of: :pedido
	accepts_nested_attributes_for :items, :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :manipulados, :reject_if => :all_blank, :allow_destroy => true
	validates_presence_of :paciente
	has_one :item
end
 

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]
 
  # GET /pedidos
  # GET /pedidos.json
  def index
    if current_user.role == "admin"
      @pedidos = Pedido.all
      @pedidos = @pedidos.sort_by{|e| e[:paciente]}
    else
      @pedidos = Pedido.where(user_id: current_user.id)
      @pedidos = @pedidos.sort_by{|e| e[:paciente]}
    end
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
    @unidades = Unidade.all
    @unidadesponto = Unidade.all
    @produtosponto = Produto.all
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
    if params[:formula_id]
      f = Formula.find(params[:formula_id])
      @itFormula = Manipulado.new
      @itFormula.formula_id = params[:formula_id]
      @itFormula.quantidade_veiculo = f.quantidade
      @itFormula.veiculo_id = f.veiculo_id
      @itFormula.unidade_id = f.unidade_id
      for ingrediente in f.ingredientes
          p = Ponto.new
          p.produto_id = ingrediente.produto_id
          p.unidade_id = ingrediente.unidade_id
          p.quantidade = ingrediente.quantidade
          @itFormula.pontos.push(p)
      end
      @pedido.manipulados.push(@itFormula)
    end
    @unidades = Unidade.all
    @unidadesponto = Unidade.all
    @produtosponto = Produto.all
  end

  # GET /pedidos/1/edit
  def edit
    @unidades = Unidade.all
    @unidadesponto = Unidade.all
    @produtosponto = Produto.all
  end


# Criamos este método que vai chamar nossa lib para gerar o PDF e depois redirecionar o user para o arquivo PDF
  def export
    @pedido = Pedido.find(params[:pedido_id])
    GeneratePdf::pedido(@pedido.id, current_user)
    redirect_to '/receita.pdf'
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @unidadesponto = Unidade.all
    @produtosponto = Produto.all    
    @unidades = Unidade.all
    @pedido = Pedido.new(pedido_params)
    puts params.class.name
    puts pedido_params.inspect
    respond_to do |format|
    @pedido.user_id = current_user.id


#      #Adiciona os ingredientes dos produtos
#    produtos_id  = params[:idproduto]
#    unidades_id  = params[:idunidade]
#    quantidades  = params[:quantidadeproduto]
#    formulaParam = params[:idFormula]

#      if produtos_id
#        produtos_id.each_with_index do |produto, index|
#          ponto = Ponto.new :produto_id => produtos_id[index], :unidade_id => unidades_id[index], :quantidade => quantidades[index]
#          puts "Ponto: " + ponto.to_s
#          for manipulados in @pedido.manipulados
#              puts "For manipulados, FORMULA ID: " + manipulados.formula_id.to_s + " E FORMULA INDEX: " + formulaParam[index]
#              if manipulados.formula_id == formulaParam[index]
#                  puts "Achou manipulado"
#                  manipulados.pontos.push(ponto)
#              end
#          end
#        end
#      end


      if @pedido.save
        format.html { redirect_to pedidos_url, notice: 'Receita adicionada com sucesso.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    @unidades = Unidade.all
    @especialidades = Especialidade.all
    @dataProdutos = Produto.all
    @unidadesponto = Unidade.all
    @produtosponto = Produto.all    
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to pedidos_url, notice: 'Receita atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @items = Item.joins(:pedido).where(' pedidos.id = ?', @pedido.id)
    @items.destroy_all

    @manipulados = Manipulado.joins(:pedido).where(' pedidos.id = ?', @pedido.id)
    @manipulados.destroy_all

    @pedido.destroy
    @unidades = Unidade.all
    @unidadesponto = Unidade.all
    @produtosponto = Produto.all
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Receita excluida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:user_id, :posologia, :especialidade_id, :paciente, items_attributes: [:id, :especialidade_id, :quantidade, :_destroy, :produto_id, :unidade_id, :posologia, :veiculo_id, :quantidade_veiculo, :unidade_veiculo_id ], manipulados_attributes: [:imprimir, :id, :formula_id, :quantidade, :_destroy, :produto_id, :posologia, :veiculo_id, :quantidade_veiculo, :unidade_id, :especialidade_id, pontos_attributes: [:id, :_destroy, :produto_id, :quantidade, :unidade_id ] ] )
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
 <%= simple_form_for(@pedido) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :paciente %>
  </div>
<br>

    <div class="produtos">
		<%= link_to_add_association 'Adicionar produto', f, :items,
		'data-association-node' => '#items ol',
		'data-association-insertion-method' => 'after', class: 'btn btn-success btn-sm' %>

		<fieldset id='items'>
			<ol>
				<%= f.fields_for :items do |item| %>
					<%= render partial: "item_fields", locals: {f: item} %>
				<% end %>
			</ol>
		</fieldset>
    </div>
    <br><br><br>
   <div class="manipulados">
		<%= link_to_add_association 'Adicionar fórmula', f, :manipulados,
		'data-association-node' => '#manipulados ol',
		'data-association-insertion-method' => 'after', class: 'btn btn-success btn-sm' %>

		<fieldset id='manipulados'>
			<ol>
				<%= f.fields_for :manipulados do |manipulado| %>
					<%= render partial: "manipulado_fields", locals: {f: manipulado} %>
				<% end %>
			</ol>
		</fieldset>
    </div>    

<br><br><br><br>

  <div class="form-actions">
    <%= f.button :submit, "Inserir Receita" %>
  </div>

<script type="text/javascript">
$(".selectize").selectize();
$('form').on('cocoon:after-insert', function(e, addedItem) {
  $(addedItem).find('.selectize').selectize()
});

</script>

<% end %>

app/views/pedidos/_item_fields.html.erb
<div class="nested-fields well well-compact form-inline">
	<%=  f.input :id, :as => :hidden %>
	<%= f.association :produto, 
		label_method: :descricao, 
		:label => "Produto", 
		:input_html => {class: "prodSelect selectize", :style=> "width: 300px;"},
		collection: Produto.joins(:grupos).where('grupos.especialidade_id IN (SELECT "permissaos".especialidade_id FROM "permissaos" WHERE "permissaos"."user_id" = ? ) ', current_user.id).uniq.sort_by{|e| e[:descricao]} 
	%>
	<%= f.input :quantidade, :label=> "Conc./dosagem", :input_html => {:style=> 'margin-left:30px; width: 70px'}  %>
	<%= f.association :unidade, label_method: :unidade, :input_html => {class:"unidProd selectize", :style=> 'margin-left:30px; width: 130px'} %>
	<%= f.input :posologia %>
	<%= f.association :veiculo, 
		label_method: :nome, 
		:label => "Veiculo", 
		:input_html => {class: "form-control veicSelect selectize", :style => "width: 100px;"},
		collection: Veiculo.all 
	%>
	<%= f.input :quantidade_veiculo , :label=> "Qtd", :input_html => {:style=> 'margin-left:30px; width: 70px'}  %>
	<%= f.label :unidade_veiculo_id%>
	<%= f.select :unidade_veiculo_id,
	     @unidades.map{ |c| [c.unidade, c.id] },
	     {:include_blank => true}, 
	     { :class => 'form-control col-md-3 selectize unidVeic', :style => "width: 100px;"}
	     %>	
    <%= link_to_remove_association button_tag('x', type: "button", class: "close"), f %>
</div>

<script>


	$(".grupoprod").on("change", function() {
  		var produtoNome = this.id.replace("especialidade_id", "produto_id")
$.ajax({
             url: "<%= update_produtos_path %>", // this will be routed
             type: 'GET',
             data: {
               especialidade_id: $("#" + this.id + " option:selected").val()
             },
             async: true,
             dataType: "JSON",
             error: function(XMLHttpRequest, errorTextStatus, error){
                        alert("Failed: "+error);
                    },
             success: function(data){
                // here we iterate the json result
                $("#" + produtoNome).empty();
                $("#" + produtoNome).append(new Option(" ", " "));
                for(var i in data)
                {
                  var id = data[i].id;
                  var descricao = data[i].descricao;
                  $("#" + produtoNome).append(new Option(descricao, id));
                }
             }
           });


	});
</script>

app/views/pedidos/_item_fields2.html.erb
<div class="nested-fields well well-compact form-inline">
	<h4>Produto: </h4>
	<%=  f.input :id, :as => :hidden %>
	<%= f.association :especialidade, 
		label_method: :nome, 
		:label => "Grupo", 
		:input_html => {class: "grupoprod selectize", :style=> 'width: 30px'},
		collection: Especialidade.where('id IN (SELECT "permissaos".especialidade_id FROM "permissaos" WHERE "permissaos"."user_id" = ? ) ', current_user.id,)	%>	
	<%= f.association :produto, 
		label_method: :descricao, 
		:label => "Produto", 
		:input_html => {class: "prodSelect selectize", :style => "width: 200px;"},
		collection: Produto.joins(:grupos).where('grupos.especialidade_id IN (SELECT "permissaos".especialidade_id FROM "permissaos" WHERE "permissaos"."user_id" = ? ) ', current_user.id) 
	%>
	<%=  f.input :quantidade %>
	<%= f.association :unidade, label_method: :unidade, :input_html => {class:       "selectize", :style => "width: 100px;"} %>
	<%=  f.input :posologia %>
	<%= f.association :veiculo, 
		label_method: :nome, 
		:label => "Veiculo", 
		:input_html => {class: "veicSelect selectize", :style => "width: 100px;"},
		collection: Veiculo.all 
	%>
	<%=  f.input :quantidade_veiculo %>
	<%= f.label :unidade_veiculo_id%>
	<%= f.select :unidade_veiculo_id,
	     @unidades.map{ |c| [c.unidade, c.id] },
	     {:include_blank => true}, 
	     { :class => 'form-control selectize', :style => "width: 100px;"}
	     %>
    
</div>

app/views/pedidos/_manipulado_fields.html.erb
<div class="nested-fields well well-compact form-inline">
	<%=  f.input :id, :as => :hidden %>
	<%= f.association :formula, label_method: :nome, :label => "Fórmula", :input_html => {class: "formSelect selectize", :style=> 'width: 300px'}, 
		collection: Formula.where(' (user_id = ? OR user_id = 0 OR user_id = 5 OR user_id = 3) AND especialidade_id IN (SELECT "permissaos".especialidade_id FROM "permissaos" WHERE "permissaos"."user_id" = ? ) ', current_user.id, current_user.id).uniq.sort_by{|e| e[:nome]} %>	
	
    <%= link_to_remove_association button_tag('x', type: "button", class: "close"), f %>

<br>
<br><br>

<div id="ingredientes">
<br>
     <div class="pontos">
    <%= link_to_add_association 'Adicionar Ingrediente', f, :pontos,
    'data-association-node' => '#pontos ol',
    'data-association-insertion-method' => 'after', class: 'btn btn-success btn-sm botaoAddIngrediente' %>

    <fieldset id='pontos'>
      <ol>
        <%= f.fields_for :pontos do |ponto| %>
          <%= render partial: "ponto_fields", locals: {f: ponto} %>
        <% end %>
      </ol>
    </fieldset>
    </div>

</div>
<br><br><br>
<div class="nested-fields form-inline">
  <%=  f.input :posologia %>
  <%= f.association :veiculo, 
    label_method: :nome, 
    :label => "Veiculo", 
    :input_html => {class: "veicSelect", style: "width: 170px;"},
    collection: Veiculo.all 
  %>
  <%=  f.input :quantidade_veiculo, :input_html => {style: "width: 100px;"} %>
  <%= f.association :unidade, label_method: :unidade, :input_html => {class: "unidVeic", style: "width: 100px;"} %>
</div>

</div>

<script>


	$(".grupoprod").on("change", function() {
  		var produtoNome = this.id.replace("especialidade_id", "formula_id")
$.ajax({
             url: "<%= update_formulas_path %>", // this will be routed
             type: 'GET',
             data: {
               especialidade_id: $("#" + this.id + " option:selected").val()
             },
             async: true,
             dataType: "JSON",
             error: function(XMLHttpRequest, errorTextStatus, error){
                        alert("Failed: "+error);
                    },
             success: function(data){
                // here we iterate the json result
                $("#" + produtoNome).empty();
                $("#" + produtoNome).append(new Option(" ", " "));
                for(var i in data)
                {
                  var id = data[i].id;
                  var nome = data[i].nome;
                  $("#" + produtoNome).append(new Option(nome, id));
                }
             }
           });


	});

$(".formSelect").on("change",carregaDados);

    $(".formSelect").ready(function(event) {
      carregaDados();
    });

function carregaDados()
  {
      var elemento = "";
      var evento   = false;
      if (this.id == null)
      {
        elemento = document.querySelector(".formSelect");
        evento = false;
      }
      else
      {
        elemento = this;
        evento = true;
      }

      var formulaNome = elemento.id;
      var formula     = $("#" + elemento.id + " option:selected").val();
      var objObservacoes = elemento.id.replace("formula_id", "observacoes");
      var divPai = $( elemento.id ).parent().id;
      var htmlAppend = "";
      var veiculoNome = elemento.id.replace("formula_id", "veiculo_id")
      var veiculoQuantidade = elemento.id.replace("formula_id", "quantidade_veiculo")
      var veiculoUnidade = elemento.id.replace("formula_id", "unidade_id")
      var formulaQuantidade = elemento.id.replace("formula_id", "quantidade")

$.ajax({
             url: "<%= update_ingredientes_path %>", // this will be routed
             type: 'GET',
             data: {
               formula_id: $("#" + elemento.id + " option:selected").val()
             },
             async: true,
             dataType: "JSON",
             error: function(XMLHttpRequest, errorTextStatus, error){
                        alert("Failed: "+error);
                    },
             success: function(data){
                // here we iterate the json result
                htmlAppend += " <div id='" + objObservacoes + "' class='" + objObservacoes + "' name='" + objObservacoes + "' >"; 
                htmlAppend += "<table>"
                if ((evento == true))
                {
                  //primeiro exclui os existentes
                  var ingreditentesAntigos = elemento.parentNode.parentNode.querySelectorAll(".closePontos");
                  console.log(ingreditentesAntigos);
                  for (var olds = 0; olds < ingreditentesAntigos.length; olds++)
                    {
                        ingreditentesAntigos[olds].click();
                    }
                for(var i in data)
                  {
                    var produto_id      = data[i].produto_id;
                    var produto_nome    = data[i].produto_descricao;
                    var unidade_unidade = data[i].unidade.unidade;
                    var unidade_id      = data[i].unidade.id;
                    var quantidade      = data[i].quantidade;
                    var editar          = data[i].editar;
                    elemento.parentNode.parentNode.querySelector(".botaoAddIngrediente").click();

                    var p = elemento.parentNode.parentNode.querySelectorAll(".PontoprodSelect")[0]
                    var q = elemento.parentNode.parentNode.querySelectorAll(".Pontoprodqtd")[0]
                    var s = elemento.parentNode.parentNode.querySelectorAll(".Pontoprodunidade")[0]
                    //while (p.options.length > 0) {
                    //  p.remove(p.options.length - 1);
                    //}

                    //while (s.options.length > 0) {
                     // s.remove(s.options.length - 1);
                    //}  
                    p.value = produto_id;
                    q.value = quantidade;                  
                    s.value = unidade_id
                    //var opt = document.createElement('option');

                    //opt.text = produto_nome;
                    //opt.value = produto_id;
                    //p.add(opt, null);

                    //var opt2 = document.createElement('option');

                    //opt2.text = unidade_unidade;
                    //opt2.value = unidade_id;
                    //s.add(opt2, null);

                   


                    /*
                    htmlAppend += "<th><tr> <td>Produto</td> <td></td> <td></td> <td>Quantidade</td> <td></td> <td>Unidade</td> </tr></th>"
                    htmlAppend += "<tr>";
                    htmlAppend += "<td>";
                    htmlAppend += "<input type='text' name='nomeproduto[]' value='" + produto_nome + "' readonly >";
                    htmlAppend += "</td>";
                    htmlAppend += "<td>";
                    htmlAppend += "<input type='hidden' name='idproduto[]' value='" + produto_id + "' readonly>";
                    htmlAppend += "</td>";

                    htmlAppend += "<td>";
                    htmlAppend += "<input type='hidden' name='idFormula[]' value='" + formula + "' readonly>";
                    htmlAppend += "</td>";

                    htmlAppend += "<td>";
                    if (editar  != "t")
                    {
                    htmlAppend += "<input type='number' name='quantidadeproduto[]' value='" + quantidade + "' >";
                    }
                    else
                    {
                     htmlAppend += "<input type='number' name='quantidadeproduto[]' value='" + quantidade + "' >"; 
                    }
                    htmlAppend += "</td>";
                    htmlAppend += "<td>";
                    htmlAppend += "<input type='hidden' name='idunidade[]' value='" + unidade_id + "' readonly>";
                    htmlAppend += "</td>";
                    htmlAppend += "<td>";
                    htmlAppend += "<input type='text' name='unidade_unidade[]' value='" + unidade_unidade + "' readonly>";
                    htmlAppend += "</td>";                    
                    htmlAppend += "</tr>";
                    */
                  }                  
                 } 
                //htmlAppend += "</table>";
                //htmlAppend += "</div>";
                //$("#" + objObservacoes).replaceWith(htmlAppend);
                
             }
           });


$.ajax({
             url: "<%= update_veiculo_formula_index_path %>", // this will be routed
             type: 'GET',
             data: {
               formula_id: $("#" + elemento.id + " option:selected").val()
             },
             async: true,
             dataType: "JSON",
             error: function(XMLHttpRequest, errorTextStatus, error){
                        alert("Failed: "+error);
                    },
             success: function(data){
                // here we iterate the json result
                $("#" + veiculoNome).empty();
                if (data.length > 1)
                {
                    if (data[0].quantidade > 0)
                    {
                      $("#" + veiculoQuantidade).val(data[0].quantidade); 
                      $("#" + formulaQuantidade).val(1); 
                      $("#" + veiculoQuantidade).attr('disabled','disabled');
                      $("#" + formulaQuantidade).attr('disabled','disabled');
                    }
                    else
                    {
                     $("#" + veiculoQuantidade).removeAttr('disabled');
                     $("#" + formulaQuantidade).removeAttr('disabled');
                    }

                    if (data[0].veiculo_unidade != null && data[0].veiculo_unidade != 0)
                    {
                      var id = data[0].veiculo_id
                      var nome = data[0].veiculo_unidade
                      $("#" + veiculoUnidade).append(new Option(nome, id));
                    }

                    $("#" + veiculoNome).append(new Option(" ", " "));
                    for(var i in data)
                    {
                      var id = data[i].id;
                      var nome = data[i].nome;
                      $("#" + veiculoNome).append(new Option(nome, id));
                    }
                  }
                  else if (data.length == 1 ) {
                    if (data[0].quantidade > 0)
                    {
                      $("#" + veiculoQuantidade).val(data[0].quantidade); 
                      $("#" + formulaQuantidade).val(1); 
                      $("#" + veiculoQuantidade).attr('disabled','disabled');
                      $("#" + formulaQuantidade).attr('disabled','disabled');
                    }
                    else
                    {
                     $("#" + veiculoQuantidade).removeAttr('disabled');
                     $("#" + formulaQuantidade).removeAttr('disabled');
                    }
                    if (data[0].veiculo_unidade != null && data[0].veiculo_unidade != 0)
                    {
                      var id = data[0].veiculo_id
                      var nome = data[0].veiculo_unidade
                      $("#" + veiculoUnidade).empty();
                      $("#" + veiculoUnidade).append(new Option(nome, id));
                    }

                      var id = data[0].id;
                      var nome = data[0].nome;
                      $("#" + veiculoNome).append(new Option(nome, id));
                  }
                  else
                  {
                    $("#" + veiculoNome).append(new Option(" ", " "));
                  }
               }
           });

  }
</script>

app/views/pedidos/_manipulado_fields2.html.erb
<div class="nested-fields well well-compact form-inline">
	<h4>Fórmula: </h4>
	<%=  f.input :id, :as => :hidden %>
  <%= f.association :especialidade, 
		label_method: :nome, 
		:label => "Grupo", 
		:input_html => {class: "grupoprod selectize", :style => "width: 200px;"},
		collection: Especialidade.where('id IN (SELECT "permissaos".especialidade_id FROM "permissaos" WHERE "permissaos"."user_id" = ? ) ', current_user.id,) 	%>
	<%= f.association :formula, label_method: :nome, :label => "Fórmula", :input_html => {class: "formSelect selectize", :style => "width: 100px;"},
		collection: Formula.where(' (user_id = ? OR user_id = 0) AND especialidade_id IN (SELECT "permissaos".especialidade_id FROM "permissaos" WHERE "permissaos"."user_id" = ? ) ', current_user.id, current_user.id)   %>	
	<%=  f.input :quantidade %>
	<%=  f.input :posologia %>
	<%= f.association :veiculo, 
		label_method: :nome, 
		:label => "Veiculo", 
		:input_html => {class: "veicSelect"},
		collection: Veiculo.all 
	%>
	<%=  f.input :quantidade_veiculo %>
	<%= f.association :unidade, label_method: :unidade, :input_html => {class:"selectize", :style => "width: 100px;"} %>
	Imprime ingredientes ? <%= f.select :imprimir, [['Sim', true], ['Não', false]], class: "form-control" %>
<br>
<br><br>

<div id="ingredientes">
  <h4>Ingredientes:</h4>
  <%=  f.input :observacoes, :label => false, :disabled => true %>
</div>



</div>

app/views/pedidos/_ponto_fields.html.erb
<div class="nested-fields well well-compact form-inline pontosAdded">
	<%=  f.input :id, :as => :hidden %>
	<%= f.association :produto, 
		label_method: :descricao, 
		:label => "Produto", 
		:input_html => {class: "PontoprodSelect", :style=> 'width: 300px'},
		collection: Produto.joins(:grupos).where('grupos.especialidade_id IN (SELECT "permissaos".especialidade_id FROM "permissaos" WHERE "permissaos"."user_id" = ? ) ', current_user.id).uniq.sort_by{|e| e[:descricao]} 
	%>
	<%=  f.input :quantidade, :label=> "Conc./dosagem", :input_html => {class: "Pontoprodqtd", :style=> 'margin-left:30px; width: 70px'}  %>
	<%= f.association :unidade, label_method: :unidade, :input_html => {class: "Pontoprodunidade ", :style=> 'margin-left:30px; width: 100px; '} %>
    <%= link_to_remove_association button_tag('x', type: "button", class: "close closePontos"), f %>
</div>

app/views/pedidos/edit.html.erb
<h1>Editar Receita</h1>

<%= render 'form', pedido: @pedido %>
<br>
<%= link_to 'Voltar', pedidos_path %>

app/views/pedidos/index.html.erb
<h1>Receitas Emitidas</h1>
<br>
<table id="receitas" class="table table-bordered table-condensed table-stripped">
  <thead>
    <tr>
      <th>Paciente</th>
      <th>Emissão</th>
      <th>Opções</th>
    </tr>
  </thead>

  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr> 
        <td><%= pedido.paciente %></td>
        <td><%= pedido.created_at.strftime("%d/%m/%y") %></td>
        <td><%= link_to 'Editar', edit_pedido_path(pedido), class: "btn btn-primary btn-xs" %>
        <%= link_to 'Excluir', pedido, class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Tem certeza que deseja excluir ?' } %>
        <%= link_to 'Gerar Receita', pedido_export_path(pedido), target: "_blank", class: "btn btn-primary btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Adicionar Receita', new_pedido_path, class: "btn btn-primary" %>

app/views/pedidos/new.html.erb
<h1>Nova Receita</h1>

<%= render 'form', pedido: @pedido %>
<br>
<%= link_to 'Voltar', pedidos_path %>

app/views/pedidos/show.html.erb
 <%= simple_form_for(@pedido) do |f| %>
  <%= f.error_notification %>
  <h3>Visualizar Receita</h3>
<br><br><br>
  <div class="form-inputs">
    <%= f.input :paciente %>
  </div>
<br>

    <div class="produtos">
		<fieldset id='items'>
			<ol>
				<%= f.fields_for :items do |item| %>
					<%= render partial: "item_fields2", locals: {f: item} %>
				<% end %>
			</ol>
		</fieldset>
    </div>

   <div class="manipulados">
		<fieldset id='manipulados'>
			<ol>
				<%= f.fields_for :manipulados do |manipulado| %>
					<%= render partial: "manipulado_fields2", locals: {f: manipulado} %>
				<% end %>
			</ol>
		</fieldset>
    </div>    
    <br><br><br><br>
  <div class="form-actions">
    <%= link_to 'Voltar', pedidos_path, class: "btn btn-default btn-xs" %>
  </div>
<% end %>