config/routes.rb
Rails.application.routes.draw do
  
  resources :veiculos
  resources :especialidades
  resources :formulas
  resources :pedidos
  resources :update_produtos do
   get 'update_produtos'  , as: 'update_produtos'
  end
  resources :update_formulas do
   get 'update_formulas'  , as: 'update_formulas'
  end  
  resources :update_ingredientes do
   get 'update_ingredientes'  , as: 'update_ingredientes'
  end  
  resources :update_veiculo_formula do
   get 'update_veiculo_formula'  , as: 'update_veiculo_formula'
  end    
  resources :pedidos do 
      get 'export'
    end
  resources :produtos
  resources :unidades
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
    get "/editar/:id" => "users#editar", as: :editar_usuario
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diluente.rb
class Diluente < ApplicationRecord
  belongs_to :produto
  belongs_to :veiculo
end

app/models/especialidade.rb
class Especialidade < ApplicationRecord
end

app/models/formula.rb
class Formula < ApplicationRecord
	has_many :ingredientes, inverse_of: :formula
	validates_presence_of :nome
	has_one :ingrediente
	belongs_to :especialidade
	belongs_to :veiculo, optional: true
	belongs_to :unidade, optional: true
	accepts_nested_attributes_for :ingredientes, :reject_if => :all_blank, :allow_destroy => true

end

app/models/grupo.rb
class Grupo < ApplicationRecord
  belongs_to :produto
  belongs_to :especialidade
end

app/models/ingrediente.rb
class Ingrediente < ApplicationRecord
  belongs_to        :formula
  belongs_to        :produto
  belongs_to        :unidade
  belongs_to        :especialidade, optional: true
  validate :VerificaUnidadeMedida
  validates_presence_of :produto, :quantidade, :unidade

protected
  def VerificaUnidadeMedida
    quantidade_formula      = self.quantidade
    quantidade_produto      = self.produto.maximo
    unidade_formula         = self.unidade.unidade
    unidade_produto         = self.produto.unidade.unidade
    fator_produto           = self.produto.unidade.fator
    fator_formula           = self.unidade.fator
    verifica = false
    conversao_unidade_formula = quantidade_formula * fator_formula
    conversao_unidade_produto = quantidade_produto * fator_produto

    unless quantidade_produto.nil?
      if conversao_unidade_formula > conversao_unidade_produto
      	verifica = false
      	errors.add(:quantidade, 'Quantidade inválida')
      end
    end

    verifica 
 end



end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :pedido
  belongs_to :produto
  belongs_to :unidade
  belongs_to :especialidade, optional: true
  belongs_to :veiculo, optional: true
  validate :VerificaUnidadeMedida
  validates_presence_of :produto, :quantidade, :unidade

  
protected
  def VerificaUnidadeMedida

    if self.produto.nil?
        verifica = false
        errors.add(:produto, 'Produto inválido')
        return verifica
    end

    if self.quantidade.nil?
        verifica = false
        errors.add(:quantidade, 'Quantidade inválida')
        return verifica
    end


    quantidade_item	        = self.quantidade
    quantidade_produto      = self.produto.maximo
    unidade_item            = self.unidade.unidade
    unidade_produto         = self.produto.unidade.unidade
    fator_produto           = self.produto.unidade.fator
    fator_item	            = self.unidade.fator
    verifica = false
    conversao_unidade_item = quantidade_item * fator_item
    conversao_unidade_produto = quantidade_produto * fator_produto

    unless quantidade_produto.nil?
      if conversao_unidade_item > conversao_unidade_produto
      	verifica = false
      	errors.add(:quantidade, 'Quantidade inválida')
      end
    end
    verifica
 end


end

app/models/manipulado.rb
class Manipulado < ApplicationRecord
  belongs_to :pedido
  belongs_to :formula
  belongs_to :especialidade, optional: true
  belongs_to :veiculo, optional: true
  belongs_to :unidade, optional: true
  has_many   :pontos,  inverse_of: :manipulado, :dependent => :delete_all
  accepts_nested_attributes_for :pontos, :reject_if => :all_blank, :allow_destroy => true
end

app/models/pai.rb
class Pai < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
	belongs_to :user
	has_many :items, inverse_of: :pedido
	has_many :manipulados, inverse_of: :pedido
	accepts_nested_attributes_for :items, :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :manipulados, :reject_if => :all_blank, :allow_destroy => true
	validates_presence_of :paciente
	has_one :item
end
 

app/models/permissao.rb
class Permissao < ApplicationRecord
  belongs_to :user
  belongs_to :especialidade
end

app/models/ponto.rb
class Ponto < ApplicationRecord
  belongs_to :manipulado
  belongs_to :produto
  belongs_to :unidade
  validates_presence_of :produto
end

app/models/produto.rb
class Produto < ApplicationRecord
	belongs_to :unidade
	has_many :grupos, inverse_of: :produto
	has_many :diluentes, inverse_of: :produto
	validates_presence_of :descricao, :unidade
	accepts_nested_attributes_for :grupos , :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :diluentes , :reject_if => :all_blank, :allow_destroy => true

	def to_s
		descricao
	end

end

app/models/unidade.rb
class Unidade < ApplicationRecord
	belongs_to :pai
	validates_presence_of :unidade, :descricao, :pai, :fator
end

app/models/user.rb
class User < ApplicationRecord
  has_many :permissaos, inverse_of: :user
  has_many :pedidos, inverse_of: :user
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user 
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         accepts_nested_attributes_for :permissaos, :reject_if => :all_blank, :allow_destroy => true
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
end

app/controllers/formulas_controller.rb
class FormulasController < ApplicationController
  before_action :set_formula, only: [:show, :edit, :update, :destroy]

  # GET /formulas
  # GET /formulas.json
  def index
    if params[:filtro]
      @formulas = Formula.where('user_id = ?',  current_user.id)
    else
      @formulas = Formula.where('user_id = ? OR user_id = 3',  current_user.id)
    end
    @formulas = @formulas.sort_by{|e| e[:nome]}
  end

  # GET /formulas/1
  # GET /formulas/1.json
  def show
  end

  # GET /formulas/new
  def new
    @formula = Formula.new
  end

  # GET /formulas/1/edit
  def edit
  end

  # POST /formulas
  # POST /formulas.json
  def create
    @formula = Formula.new(formula_params)
    @formula.user_id = current_user.id
    respond_to do |format|
      if @formula.save
        format.html { redirect_to formulas_url, notice: 'Fórmula adicionada com sucesso.' }
        format.json { render :show, status: :created, location: @formula }
      else
        format.html { render :new }
        format.json { render json: @formula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formulas/1
  # PATCH/PUT /formulas/1.json
  def update
    respond_to do |format|
      if @formula.update(formula_params)
        format.html { redirect_to formulas_url, notice: 'Fórmula atualizada com sucesso.' }
        format.json { render :show, status: :ok, location: @formula }
      else
        format.html { render :edit }
        format.json { render json: @formula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formulas/1
  # DELETE /formulas/1.json
  def destroy
    @formula.destroy
    respond_to do |format|
      format.html { redirect_to formulas_url, notice: 'Fórmula excluida com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formula
      @formula = Formula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def formula_params
      params.require(:formula).permit(:nome, :veiculo_id, :especialidade_id, :observacoes, :quantidade, :unidade_id, :editar, ingredientes_attributes: [:id, :especialidade_id, :quantidade, :_destroy, :produto_id, :unidade_id ] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/formulas_helper.rb
module FormulasHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/formulas/_form.html.erb
<%= simple_form_for(@formula) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.association :especialidade, label_method: :nome, :label => "Especialidade", :input_html => {class: "selectize"} %>
    <%= f.association :veiculo, label_method: :nome, :label => "Veículo Padrão", :input_html => {class: "selectize"},
        collection: Veiculo.all.sort_by{|e| e[:nome]}  %>
    <%= f.input :quantidade, :label => "Quantidade padrão" %>
    <%= f.association :unidade, label_method: :descricao, :label => "Unidade Padrão", :input_html => {class: "selectize"} %>
    <%= f.input :observacoes %>
    Bloquear edição ? <%= f.select :editar, [['Não', false], ['Sim', true]], class: "form-control" %>
    <br>
    <br>
    <br>
  </div>


    <div class="produtos">
		<%= link_to_add_association 'Adicionar produto', f, :ingredientes,
		'data-association-node' => '#ingredientes ol',
		'data-association-insertion-method' => 'append', class: 'btn btn-success btn-sm' %>
<br><br><br><br><br>
<h4>Produtos da fórmula</h4>
		<fieldset id='ingredientes' >
			<ol>
				<%= f.fields_for :ingredientes do |ingrediente| %>
					<%= render partial: "ingrediente_fields", locals: {f: ingrediente} %>
				<% end %>
			</ol>
		</fieldset>
    </div>

  <div class="form-actions">
    <%= f.button :submit, "Inserir Fórmula" %>
  </div>
  <script type="text/javascript">
$(".selectize").selectize();
$('form').on('cocoon:after-insert', function(e, addedItem) {
  $(addedItem).find('.selectize').selectize()
});

</script>

<% end %>

app/views/formulas/_ingrediente_fields.html.erb
<div class="nested-fields well well-compact form-inline">
	<%=  f.input :id, :as => :hidden %>
		<%= f.association :produto, 
		label_method: :descricao, 
		:label => "Produto", 
		:input_html => {class: "prodSelect selectize", :style => "width: 200px;"},
		collection: Produto.joins(:grupos).where('grupos.especialidade_id IN (SELECT "permissaos".especialidade_id FROM "permissaos" WHERE "permissaos"."user_id" = ? ) ', current_user.id).uniq.sort_by{|e| e[:descricao]} %>
	<%=  f.input :quantidade %>
	<%= f.association :unidade, label_method: :unidade, :label => "UN", :input_html => {class:       "selectize", :style => "width: 100px;"} %>
    <%= link_to_remove_association button_tag('x', type: "button", class: "close"), f %>
</div>

<script>
	$(".grupoprod").on("change", function() {
  		var produtoNome = this.id.replace("especialidade_id", "produto_id")
$.ajax({
             url: "<%= update_produtos_path %>", // this will be routed
             type: 'GET',
             data: {
               especialidade_id: $("#" + this.id + " option:selected").val()
             },
             async: true,
             dataType: "JSON",
             error: function(XMLHttpRequest, errorTextStatus, error){
                        alert("Failed: "+error);
                    },
             success: function(data){
                // here we iterate the json result
                $("#" + produtoNome).empty();
                $("#" + produtoNome).append(new Option(" ", " "));
                for(var i in data)
                {
                  var id = data[i].id;
                  var descricao = data[i].descricao;
                  $("#" + produtoNome).append(new Option(descricao, id));
                }
             }
           });


	});
</script>

app/views/formulas/edit.html.erb
<h1>Editar Formula</h1>

<%= render 'form', formula: @formula %>

<%= link_to 'Voltar', formulas_path %>

app/views/formulas/index.html.erb
<h1>Fórmulas</h1>
<br>

<br>
<%= link_to 'Mostrar todos', formulas_path, class: "btn btn-warning btn-xs" %>
<%= link_to 'Filtrar Médico', formulas_path(filtro: true), class: "btn btn-info btn-xs" %>
<br>
<br>
<br>

<table id="formulas" class="table table-bordered table-condensed table-stripped">
  <thead>
    <tr>
      <th>Nome da Fórmula</th>
      <th>Emissão</th>
      <th>Opções</th>
    </tr>
  </thead>

  <tbody>
    <% @formulas.each do |formula| %>
      <tr>
        <td><%= formula.nome %></td>
        <td><%= formula.created_at.strftime("%d/%m/%y") %></td>
        <% if current_user.role == "admin" %>
        <td><%= link_to 'Editar', edit_formula_path(formula), class: "btn btn-primary btn-xs" %>
        <%= link_to 'Excluir', formula, class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Tem certeza que deseja excluir ?' } %>
        <%= link_to 'Usar', new_pedido_path(formula_id: formula.id), class: "btn btn-success btn-xs" %>
        <% elsif current_user.id == formula.user_id %>
        <td><%= link_to 'Editar', edit_formula_path(formula), class: "btn btn-primary btn-xs" %>
        <%= link_to 'Excluir', formula, class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Tem certeza que deseja excluir ?' } %>
        <%= link_to 'Usar', new_pedido_path(formula_id: formula.id), class: "btn btn-success btn-xs" %>
        <% elsif current_user.id != formula.user_id %>
        <td><%= link_to 'Visualizar', formula_path(formula), class: "btn btn-primary btn-xs" %>
        <%= link_to 'Usar', new_pedido_path(formula_id: formula.id), class: "btn btn-success btn-xs" %>
        <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Inserir Fórmula', new_formula_path, class: "btn btn-primary" %>

app/views/formulas/new.html.erb
<h1>Inserir nova Formula</h1>

<%= render 'form', formula: @formula %>

<%= link_to 'Back', formulas_path %>

app/views/formulas/show.html.erb
<%= simple_form_for(@formula) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.association :especialidade, label_method: :nome, :label => "Especialidade", :input_html => {} %>
    <%= f.association :veiculo, label_method: :nome, :label => "Veículo Padrão", :input_html => {} %>
    <%= f.input :observacoes %>
  </div>


    <div class="produtos">
<br><br><br><br><br>
<h4>Produtos da fórmula</h4>
		<fieldset id='ingredientes' >
			<ol>
				<%= f.fields_for :ingredientes do |ingrediente| %>
					<%= render partial: "ingrediente_fields", locals: {f: ingrediente} %>
				<% end %>
			</ol>
		</fieldset>
    </div>
<% end %>

<%= link_to 'Voltar', formulas_path, class: "btn btn-default"  %>