config/routes.rb
Rails.application.routes.draw do
  
  resources :veiculos
  resources :especialidades
  resources :formulas
  resources :pedidos
  resources :update_produtos do
   get 'update_produtos'  , as: 'update_produtos'
  end
  resources :update_formulas do
   get 'update_formulas'  , as: 'update_formulas'
  end  
  resources :update_ingredientes do
   get 'update_ingredientes'  , as: 'update_ingredientes'
  end  
  resources :update_veiculo_formula do
   get 'update_veiculo_formula'  , as: 'update_veiculo_formula'
  end    
  resources :pedidos do 
      get 'export'
    end
  resources :produtos
  resources :unidades
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users
  resources :users
    get "/editar/:id" => "users#editar", as: :editar_usuario
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diluente.rb
class Diluente < ApplicationRecord
  belongs_to :produto
  belongs_to :veiculo
end

app/models/especialidade.rb
class Especialidade < ApplicationRecord
end

app/models/formula.rb
class Formula < ApplicationRecord
	has_many :ingredientes, inverse_of: :formula
	validates_presence_of :nome
	has_one :ingrediente
	belongs_to :especialidade
	belongs_to :veiculo, optional: true
	belongs_to :unidade, optional: true
	accepts_nested_attributes_for :ingredientes, :reject_if => :all_blank, :allow_destroy => true

end

app/models/grupo.rb
class Grupo < ApplicationRecord
  belongs_to :produto
  belongs_to :especialidade
end

app/models/ingrediente.rb
class Ingrediente < ApplicationRecord
  belongs_to        :formula
  belongs_to        :produto
  belongs_to        :unidade
  belongs_to        :especialidade, optional: true
  validate :VerificaUnidadeMedida
  validates_presence_of :produto, :quantidade, :unidade

protected
  def VerificaUnidadeMedida
    quantidade_formula      = self.quantidade
    quantidade_produto      = self.produto.maximo
    unidade_formula         = self.unidade.unidade
    unidade_produto         = self.produto.unidade.unidade
    fator_produto           = self.produto.unidade.fator
    fator_formula           = self.unidade.fator
    verifica = false
    conversao_unidade_formula = quantidade_formula * fator_formula
    conversao_unidade_produto = quantidade_produto * fator_produto

    unless quantidade_produto.nil?
      if conversao_unidade_formula > conversao_unidade_produto
      	verifica = false
      	errors.add(:quantidade, 'Quantidade inválida')
      end
    end

    verifica 
 end



end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :pedido
  belongs_to :produto
  belongs_to :unidade
  belongs_to :especialidade, optional: true
  belongs_to :veiculo, optional: true
  validate :VerificaUnidadeMedida
  validates_presence_of :produto, :quantidade, :unidade

  
protected
  def VerificaUnidadeMedida

    if self.produto.nil?
        verifica = false
        errors.add(:produto, 'Produto inválido')
        return verifica
    end

    if self.quantidade.nil?
        verifica = false
        errors.add(:quantidade, 'Quantidade inválida')
        return verifica
    end


    quantidade_item	        = self.quantidade
    quantidade_produto      = self.produto.maximo
    unidade_item            = self.unidade.unidade
    unidade_produto         = self.produto.unidade.unidade
    fator_produto           = self.produto.unidade.fator
    fator_item	            = self.unidade.fator
    verifica = false
    conversao_unidade_item = quantidade_item * fator_item
    conversao_unidade_produto = quantidade_produto * fator_produto

    unless quantidade_produto.nil?
      if conversao_unidade_item > conversao_unidade_produto
      	verifica = false
      	errors.add(:quantidade, 'Quantidade inválida')
      end
    end
    verifica
 end


end

app/models/manipulado.rb
class Manipulado < ApplicationRecord
  belongs_to :pedido
  belongs_to :formula
  belongs_to :especialidade, optional: true
  belongs_to :veiculo, optional: true
  belongs_to :unidade, optional: true
  has_many   :pontos,  inverse_of: :manipulado, :dependent => :delete_all
  accepts_nested_attributes_for :pontos, :reject_if => :all_blank, :allow_destroy => true
end

app/models/pai.rb
class Pai < ApplicationRecord
end

app/models/pedido.rb
class Pedido < ApplicationRecord
	belongs_to :user
	has_many :items, inverse_of: :pedido
	has_many :manipulados, inverse_of: :pedido
	accepts_nested_attributes_for :items, :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :manipulados, :reject_if => :all_blank, :allow_destroy => true
	validates_presence_of :paciente
	has_one :item
end
 

app/models/permissao.rb
class Permissao < ApplicationRecord
  belongs_to :user
  belongs_to :especialidade
end

app/models/ponto.rb
class Ponto < ApplicationRecord
  belongs_to :manipulado
  belongs_to :produto
  belongs_to :unidade
  validates_presence_of :produto
end

app/models/produto.rb
class Produto < ApplicationRecord
	belongs_to :unidade
	has_many :grupos, inverse_of: :produto
	has_many :diluentes, inverse_of: :produto
	validates_presence_of :descricao, :unidade
	accepts_nested_attributes_for :grupos , :reject_if => :all_blank, :allow_destroy => true
	accepts_nested_attributes_for :diluentes , :reject_if => :all_blank, :allow_destroy => true

	def to_s
		descricao
	end

end

app/models/unidade.rb
class Unidade < ApplicationRecord
	belongs_to :pai
	validates_presence_of :unidade, :descricao, :pai, :fator
end

app/models/user.rb
class User < ApplicationRecord
  has_many :permissaos, inverse_of: :user
  has_many :pedidos, inverse_of: :user
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user 
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


         accepts_nested_attributes_for :permissaos, :reject_if => :all_blank, :allow_destroy => true
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy, :update_produtos]



  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all
    @produtos = @produtos.sort_by{|e| e[:descricao]}
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to produtos_url, notice: 'Produto adicionado com sucesso.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to produtos_url, notice: 'Produto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:descricao, :observacoes, :maximo, :unidade_id, grupos_attributes: [:id, :especialidade_id, :_destroy], diluentes_attributes: [:id, :veiculo_id, :_destroy] )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/formulas_helper.rb
module FormulasHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/produtos/_diluente_fields.html.erb
<div class="nested-fields well well-compact form-inline">
	<%=  f.input :id, :as => :hidden %>
	<%= f.association :veiculo, label_method: :nome, :label => "Veículo", :input_html => {class: "selectize" , :style => "width: 200px;"} %>	
    <%= link_to_remove_association button_tag('x', type: "button", class: "close"), f %>
</div>

app/views/produtos/_form.html.erb
<%= simple_form_for(@produto) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :descricao %>
    <%= f.input :observacoes %>
    <%= f.input :sinonimo, :label => "Sinônimo" %>
    <%= f.input :maximo %>
    <%= f.association :unidade, label_method: :unidade, :label => "Em", :input_html => {class: "unidadeProduto"} %>
  </div>

  <div class="especialidadesProd">
    <%= link_to_add_association 'Adicionar Grupo', f, :grupos,
    'data-association-node' => '#especialidadesProd ol',
    'data-association-insertion-method' => 'after', class: 'btn btn-success btn-sm' %>

    <fieldset id='especialidadesProd'>
      <ol>
        <%= f.fields_for :grupos do |item| %>
          <%= render partial: "grupo_fields", locals: {f: item} %>
        <% end %>
      </ol>
    </fieldset>
  </div>


  <div class="veiculosProd">
    <%= link_to_add_association 'Adicionar Veículo', f, :diluentes,
    'data-association-node' => '#veiculosProd ol',
    'data-association-insertion-method' => 'after', class: 'btn btn-success btn-sm' %>

    <fieldset id='veiculosProd'>
      <ol>
        <%= f.fields_for :diluentes do |item| %>
          <%= render partial: "diluente_fields", locals: {f: item} %>
        <% end %>
      </ol>
    </fieldset>
  </div>



  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<script type="text/javascript">
$(".selectize").selectize();
$('form').on('cocoon:after-insert', function(e, addedItem) {
  $(addedItem).find('.selectize').selectize()
});

</script>

<% end %>

app/views/produtos/_grupo_fields.html.erb
<div class="nested-fields well well-compact form-inline">
	<%=  f.input :id, :as => :hidden %>
	<%= f.association :especialidade, label_method: :nome, :label => "Grupo", :input_html => {class:       "selectize", :style => "width: 200px;"} %>	
    <%= link_to_remove_association button_tag('x', type: "button", class: "close"), f %>
</div>

app/views/produtos/edit.html.erb
<h1>Editar Produto</h1>

<%= render 'form', produto: @produto %>

<br>
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cadastro de produtos</h1>
<br>
<table id="produtos" class="table table-bordered table-condensed table-stripped">
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Observacoes</th>
      <th>Qtd. Máxima</th>
      <th>Unidade</th>
      <th>Opções</th>
    </tr>
  </thead>
  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.descricao %></td>
        <td><%= produto.observacoes %></td>
        <td><%= produto.maximo %></td>
        <td><%= produto.unidade.unidade %></td>
        <td> 
            <% if current_user.role == "admin" %>
            <%= link_to 'Editar', edit_produto_path(produto), class: "btn btn-primary btn-xs" %>
            <%= link_to 'Excluir', produto, class: "btn btn-danger btn-xs", method: :delete, data: { confirm: 'Tem certeza que deseja excluir ?' }%>
            <% else %>
            <%= link_to 'Visualizar', produto_path(produto), class: "btn btn-primary btn-xs" %>
            <% end %>
        </td>        
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if current_user.role == "admin" %>
  <%= link_to 'Adicionar Produto', new_produto_path, class: "btn btn-primary" %>
<%end%>

app/views/produtos/new.html.erb
<h1>Inserir Produto</h1>

<%= render 'form', produto: @produto %>
<br>
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @produto.descricao %>
</p>

<p>
  <strong>Observacoes:</strong>
  <%= @produto.observacoes %>
</p>


<%= link_to 'Editar', edit_produto_path(@produto) %> |
<%= link_to 'Voltar', produtos_path %>